### ISSUE TITLE
Suggestion: Machine Sounds

### ISSUE THREAD

**Issue by samuelt005** [ProjectHDS/ModularController#1]
Option to add custom sounds to each controller when they are active.

**Comment by friendlyhj** [comment]
Add `"activated_sound": "modularcontroller:machine_activated_industry"` entry to your machine json.
The mod provides three sounds to use:
* `modularcontroller:machine_activated_industry`
* `modularcontroller:machine_activated_science_fiction`
* `modularcontroller:machine_activated_steam`
