### ISSUE TITLE
修改控制器模型时出现透视

### ISSUE THREAD

**Issue by lunareclipse-64** [ProjectHDS/ModularController#2]
将完整的控制器方块模型修改为不完整方块，会在与另一完整方块交界面处不渲染该方块材质，即出现透视。

**Comment by friendlyhj** [comment]
Fixed by https://github.com/ProjectHDS/ModularController/commit/9c58d925e037b6389c71e595ec2b40421b16ba67

Add
```json
"controller": {
    "fullblock": false
}
```
