### ISSUE TITLE
Game crashes on PreInit if machine json(s) are not present / incomplete

### ISSUE THREAD

**Issue by RedRaspberry** [ProjectHDS/ModularController#4]
Game Version: Latest 1.12.2 Forge (14.23.5.2860)
Mod Version: 1.1.5 
(Using with version 1.10.0 of Modular Machinery, 1.10 of Modular Diversity)

Description:
Attempting to launch minecraft with no json files present in the Machinery or Recipe folder of the modular machinery config will cause a crash in PreInit. This also seems to occur if there are json files present in the machine folder that do not have associated recipes, or vice versa. 

A crashlog is attached.

[crash-2022-01-18_16.35.22-client.txt](https://github.com/ProjectHDS/ModularController/files/7892556/crash-2022-01-18_16.35.22-client.txt)

**Comment by friendlyhj** [comment]
Fixed in 1.3.1. It is not a serious bug. So I am not going to fix it in 1.1.x version.
I suggest using [gugu utils](https://www.curseforge.com/minecraft/mc-mods/gugu-utils) to replace Modular Diversity.
